### ISSUE TITLE
Xbox supports immediate mode rendering

### ISSUE THREAD

**Issue by JayFoxRox** [brentdc-nz/PCSX-ReloadedX#2]
https://github.com/marty28/PCSX-ReloadedX/blob/08d568c3e1be175bd52fbc736f94553ca0b41f4b/xbox/fakeglx/fakeglx09.c#L980-L988

This is not true for Xbox Direct3D. The Xbox GPU (NV2A) supports immediate mode rendering.
Microsoft added hardware extensions which should be available as:

- `D3DDevice::Begin`
- `D3DDevice::SetVertexData4f` and friends
- `D3DDevice::End`

The mapping is the one that you'd expect from the nvidia OpenGL implementation; vertex attribute 0 submits the vertex (equivalent to `glVertex4f`).

The data would be inlined into the pushbuffers. You can avoid the call overhead, by constructing a custom pushbuffer from scratch to get zero-copy for extra performance. You can then use `D3DDevice::RunPushBuffer` or something to submit it.
Wether this is faster: I don't know. It certainly depends on what kind of data you submit.

Also check @XQEMU code or nxdk source-code for more information. @XboxDev community in general will have knowledge about this (although we might not always know what's best for performance yet).

**Comment by marty28** [comment]
Thank you for the info, we were going to look at this as we expected to get a nice boost from not having to buffer everything up, the comment was left over from the PC source. The contributor FreakDave also put forward this suggestion and did some testing, not sure how far he got with it tho.

I'm definitely keen to have a stab at it myself again at some point.

Cheers

**Comment by marty28** [comment]
Thank you for the info, we were going to look at this as we expected to get a nice boost from it, the comment was left over from the PC source. The contributor FreakDave also put forward this suggestion and did some testing, not sure how far he got with it tho.

I'm definitely keen to have a stab at it myself again at some point.

Cheers

**Comment by brentdc-nz** [comment]
Thank you for the info, we were going to look at this as we expected to get a nice boost from it, the comment was left over from the PC source. The contributor FreakDave also put forward this suggestion and did some testing, not sure how far he got with it tho.

I'm definitely keen to have a stab at it myself again at some point. I will checkout XboxDev and xqemu.

Cheers

**Comment by brentdc-nz** [comment]
Have now rewritten to test using immediate mode and found the speed gain was not as great as expected. I'm not going to commit as a fork until I can get more speed out of it.
